select * 
from fact_sales fs
join dim_customers dc
	on fs.customer_key = dc.customer_key
join dim_products dp
	on fs.product_key = dp.product_key;

select * from fact_sales fs;
select * from dim_customers;
select * from dim_products;

-- check duplicates for each table --

select customer_key, count(*) as total_count 
from dim_customers dc
group by customer_key
having total_count > 1;

select product_key, count(*) as total_count 
from dim_products
group by product_key
having total_count > 1;

with cte_dupe as 
(
select *, 
row_number() over(partition by order_number, product_key, customer_key, order_date, shipping_date, due_date, sales_amount, quantity, price) as row_num
from fact_sales
)
select * 
from cte_dupe
where row_num >1;

-- 2 ways to calculate age---------

select year(curdate()) - year(birthdate) as age
from dim_customers dc;

select timestampdiff(YEAR, birthdate, CURDATE())
from dim_customers;

-- Find the date of the first and last order --
select min(order_date), max(order_date)
from fact_sales
where order_date != '';

-- How many years of sales are available ----
select min(order_date), max(order_date), 
	timestampdiff(YEAR, min(order_date),max(order_date)) as order_range_years
from fact_sales
where order_date != '';

-- Find the youngest and oldest customer ---
select min(timestampdiff(YEAR, birthdate, CURDATE())) as Youngest, 
	max(timestampdiff(YEAR, birthdate, CURDATE())) as Oldest
from dim_customers

-- Find the total Sales ---
select sum(sales_amount)
from fact_sales;

-- Find how many items are sold --
select sum(quantity) as total_sold
from fact_sales;

-- Find the average selling price --
select avg(price) as avg_price
from fact_sales;

-- Find the total number of orders // one customer can purchase 3 items in one order **important to use distinct--
select count(distinct order_number) as total_order
from fact_sales;

-- Find the total number of products --
select count(product_id) total_products
from dim_products

-- Find the total number of customers --
select count(customer_key) as total_customers
from dim_customers;

-- Find the total number of customers that has placed an order --
select count(distinct customer_key) as total_customers
from fact_sales;

-- Generate a report that shows all key metrics of the business ---------
select 'Total_sales' as measure_name, sum(sales_amount) from fact_sales
union all
select 'Total_products' as measure_name, count(product_id) total_products from dim_products
union all
select 'Total_quantity' as measure_name, sum(quantity) from fact_sales
union all
select 'Average Price' as measure_name, avg(price) from fact_sales
union all
select 'Total Nr._orders' as measure_name, count(distinct order_number) from fact_sales
union all
select 'Total Nr._products' as measure_name, count(distinct product_name) from dim_products
union all
select 'Total Nr._customers' as measure_name, count(distinct customer_key) from dim_customers;

-- Find total customers by countries --
select country, count(customer_key) as customer_number
from dim_customers
group by country
order by 2 desc;

-- Find total customers by gender --
select gender, count(customer_key) as customer_number
from dim_customers
group by gender;

-- Find total products by category --
select category, count(product_key) as product_count
from dim_products
group by category;

-- Compare sales per product line--
select product_line, avg(price) as avg_price, sum(quantity) as total_quantity, sum(sales_amount) as total_sales
from fact_sales fs
join dim_products dp
	on fs.product_key = dp.product_key
where date_format(fs.order_date,'%Y') = 2011
group by 1;

-- What is the average costs in each category --
select category, round(avg(cost),2)
from dim_products
group by category;

-- Find total revenue generated by each customer per year--
select concat(dc.first_name,' ', dc.last_name) as Full_name, sum(sales_amount) as total_sales
from fact_sales fs
join dim_customers dc
	on fs.customer_key = dc.customer_key
where date_format(fs.order_date,'%Y') = 2012
group by full_name
order by 2 desc
limit 10;

select dc.first_name, dc.last_name, sum(fs.sales_amount) as total_sales
from fact_sales fs 
join dim_customers dc
	on fs.customer_key = dc.customer_key
where first_name ='Jordan' and last_name = 'Turner';

-- Which 10 products generate the highest revenue --
select *
from 
	(select dp.product_name, sum(sales_amount), 
			row_number() over (order by sum(sales_amount) desc) as ranking
	from fact_sales fs
	join dim_products dp 
		on fs.product_key = dp.product_key
	group by dp.product_name
	order by 2 desc) sales_rank
where ranking <= 10;

-- Find the 10 worst performing products in terms of sales --
select *
from 
	(select dp.product_name, sum(sales_amount), 
			row_number() over (order by sum(sales_amount) asc) as ranking
	from fact_sales fs
	join dim_products dp 
		on fs.product_key = dp.product_key
	group by dp.product_name
	order by 2 asc) sales_rank
where ranking <= 10;

-- Find products that has no sale by subcategory --
select distinct dp.subcategory
from dim_products dp 
where dp.subcategory not in 
						(select distinct dp.subcategory
						from fact_sales fs
						join dim_products dp 
							on fs.product_key = dp.product_key);

-- Compare products purchased by marital status --

select dp.subcategory, dc.marital_status, 
		sum(fs.sales_amount) as total_sales, 
		rank() over(partition by dc.marital_status order by sum(fs.sales_amount) desc) as rank_nr
from fact_sales fs
join dim_customers dc
	on fs.customer_key = dc.customer_key
join dim_products dp
	on fs.product_key = dp.product_key
group by dp.subcategory, dc.marital_status;

-- compare table side by side of total sales by gender --

with cte_gender (subcategory, gender, total_sales, ranking) as
(
select dp.subcategory, dc.gender, sum(fs.sales_amount), 
		dense_rank() over(partition by dc.gender order by sum(fs.sales_amount) desc)
from fact_sales fs
join dim_customers dc
	on fs.customer_key = dc.customer_key
join dim_products dp
	on fs.product_key = dp.product_key
group by dp.subcategory, dc.gender
)
select *
from cte_gender cg1
join cte_gender cg2
	on cg1.subcategory = cg2.subcategory
where cg1.gender ='female'
		and cg2.gender = 'male';

-- order count per customer --
select dc.customer_key, concat(dc.first_name, ' ', dc.last_name) as full_name, count(*) as order_count
from dim_customers dc 
join fact_sales fs
	on dc.customer_key = fs.customer_key
group by customer_key, full_name
order by 3 desc; 

-- total months ordered per customer--
select dc.customer_key, min(order_date) as min_order, MAX(order_date) as max_order, 
		timestampdiff(MONTH,min(order_date), MAX(order_date)) as total_months
from dim_customers dc 
join fact_sales fs
	on dc.customer_key = fs.customer_key
group by dc.customer_key
order by 4 desc;

-- calculate total months where each customer ordered --
with cte_customer (customer_key, min_order, max_order, months_stayed) as
(select dc.customer_key, min(order_date) as min_order, MAX(order_date) as max_order, 
timestampdiff(MONTH,min(order_date), MAX(order_date))
from dim_customers dc 
join fact_sales fs
	on dc.customer_key = fs.customer_key
group by dc.customer_key
order by 4 desc)
select sum(months_stayed) as total_months
from cte_customer;

-- calculate average order value --
select (sum(sales_amount))/(count(distinct order_number)) as Avg_order_value
from fact_sales;

-- Sales trend per month--
select date_format(order_date, '%Y-%m') as order_month, sum(sales_amount) as total_sales
from fact_sales
group by order_month
having order_month is not null
order by 1 asc;

-- Sales trend per year --
select date_format(order_date, '%Y') as order_year, sum(sales_amount)
from fact_sales
group by order_year
having order_year is not null
order by 1 asc;